language: nix
sudo: required

services:
  - docker

env:
  - NIXPKGS=nixos-unstable CMD=helm VERSION=2.11.0
  - NIXPKGS=nixos-unstable CMD=kubectl VERSION=1.11.5
  - NIXPKGS=nixos-unstable CMD=kubectl VERSION=1.11.6
  - NIXPKGS=nixos-unstable CMD=kubectl VERSION=1.12.0
  - NIXPKGS=nixos-unstable CMD=kubectl VERSION=1.12.1
  - NIXPKGS=nixos-unstable CMD=kubectl VERSION=1.12.2
  - NIXPKGS=nixos-unstable CMD=kubectl VERSION=1.12.3
  - NIXPKGS=nixos-unstable CMD=kubectl VERSION=1.13.1
  - NIXPKGS=nixos-unstable CMD=kubectl VERSION=1.13.2
  - NIXPKGS=nixos-unstable CMD=kubectl VERSION=1.13.3
  - NIXPKGS=nixos-unstable CMD=kubectl VERSION=1.13.4
  - NIXPKGS=nixos-18.09 CMD=helm VERSION=2.11.0
  - NIXPKGS=nixos-18.09 CMD=kubectl VERSION=1.11.5
  - NIXPKGS=nixos-18.09 CMD=kubectl VERSION=1.11.6
  - NIXPKGS=nixos-18.09 CMD=kubectl VERSION=1.12.0
  - NIXPKGS=nixos-18.09 CMD=kubectl VERSION=1.12.1
  - NIXPKGS=nixos-18.09 CMD=kubectl VERSION=1.12.2
  - NIXPKGS=nixos-18.09 CMD=kubectl VERSION=1.12.3
  - NIXPKGS=nixos-18.09 CMD=kubectl VERSION=1.13.1
  - NIXPKGS=nixos-18.09 CMD=kubectl VERSION=1.13.2
  - NIXPKGS=nixos-18.09 CMD=kubectl VERSION=1.13.3
  - NIXPKGS=nixos-18.09 CMD=kubectl VERSION=1.13.4

before_install:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix authtoken $CACHIX_AUTHTOKEN
  - cachix use k8s-deploy

script:
  - nix-build --no-out-link -I nixpkgs=channel:$NIXPKGS -A "all.$CMD.\"$VERSION\"" nix/default.nix | cachix push k8s-deploy

jobs:
  include:
    - stage: deploy
      script:
        - 'docker build --pull -t umweltdk/k8s-deploy .'
        - 'nix-build --no-out-link -I nixpkgs=channel:nixos-18.09 -A package nix/default.nix | cachix push k8s-deploy'
        - 'docker build --pull --build-arg nixpkgs=channel:nixos-18.09 -t umweltdk/k8s-deploy:nixos-stable nix'
        - 'nix-build --no-out-link -I nixpkgs=channel:nixos-unstable -A package nix/default.nix | cachix push k8s-deploy'
        - 'docker build --pull --build-arg nixpkgs=channel:nixos-unstable -t umweltdk/k8s-deploy:nixos-unstable nix'
      deploy:
        provider: script
        script: "ci/deploy.sh"
        on:
          repo: 'umweltdk/k8s-deploy'
          branch: master
