sudo: required

services:
  - docker

script:
  - docker build --pull -t umweltdk/k8s-deploy .

deploy:
  provider: script
  script: echo -n "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push umweltdk/k8s-deploy:latest
  on:
    repo: 'umweltdk/k8s-deploy'
    branch: master
